int main()
         {
             int n;
             scanf("%d",&n);
             if(n>50)
                {
                    if(n>70)
                    {
                        if(n>80)
                        {
                            if(n>90)
                                printf("A");
                            else
                                printf("D");
                        }
                        else
                            printf("B");
                    }
                    else
                        printf("C");
                }
                else
                    if(n<33)
                       {
                           if(n<20)
                            printf("F");
                           else
                            printf("E");
                       }
                    else
                        printf("E");
         }
